spring:
  config:
    import: classpath:api-secret.properties
  datasource:
    url: jdbc:postgresql://${DB_ENDPOINT_DEV}?sslmode=require&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true

oauth:
  client:
    google:
      credentials:
        client-id: ${GOOGLE_OAUTH_CLIENT_ID}
        client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
        redirect-uri: http://mypubcafe.com/oauth/callback
      provider:
        uri:
          user-info: https://www.googleapis.com/oauth2/v2/userinfo
          token: https://oauth2.googleapis.com/token

jwt:
  secret-key: your-very-secure-and-long-secret-key-for-hs256-signing
  access-expiration-time: 1800000       # 30분
  refresh-expiration-time: 604800000    # 1주
