CREATE TABLE member
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL UNIQUE,
    role       VARCHAR(255),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE member_profile
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id         BIGINT       NOT NULL UNIQUE,
    alias             VARCHAR(255) NOT NULL UNIQUE,
    display_name      VARCHAR(32)  NOT NULL,
    introduction      VARCHAR(256),
    country           CHAR(2)      NOT NULL,
    contact           VARCHAR(255),
    languages         TEXT,
    links             TEXT,
    profile_image_url VARCHAR(255),
    banner_image_url  VARCHAR(255),

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_member_profile_member_id FOREIGN KEY (member_id) REFERENCES member (id)
);
