SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE member_profile;
TRUNCATE TABLE member;

ALTER TABLE member_profile ALTER COLUMN id RESTART WITH 100;
ALTER TABLE member ALTER COLUMN id RESTART WITH 100;

SET REFERENTIAL_INTEGRITY TRUE;